In [49]:
import torch
print(torch.__version__)

2.9.0+cu126


In [50]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"using {torch.cuda.get_device_name(0)}")

GPU is available
using Tesla T4


Creating a Tensor


In [51]:
#using empty
a = torch.empty(2,3)
#  allocating space for tensor in memory

In [52]:
# check type
type(a)


torch.Tensor

In [53]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [54]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [55]:
# using rand
torch.rand(2,3)

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [56]:
# manual_seed

# to enable reproducibility aka if i run torch.rand then it will give me same values each time

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [57]:
# using tensor 
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [58]:
#other ways

#arange

torch.arange(2,10,2)

# using linspace 
torch.linspace(0,10,10)

#using eye

#diagonal items would be one and others woudld be zero

torch.eye(5)

# using full
torch.full((3,3),5)
# in this we can define its row and columns and also the element or the number 




tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

Tensor Shapes

In [59]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [60]:
x.shape

torch.Size([2, 3])

In [61]:
# used to copy the shape of desired tensor
torch.empty_like(x)
torch.zeros_like(x)
torch.ones_like(x)
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tesnor Datatypes

In [62]:
#find data type
x.dtype
#assigned data type
y = torch.tensor([[1.0,2.0,3.0],[4.0,3.1,2.1]],dtype=torch.int64)

# using to()
x.to(torch.float32)


tensor([[1., 2., 3.],
        [4., 5., 6.]])

#**Mathematical Operartions**

1. Scalar Operations

In [63]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [64]:
#Addition

x+2

#Substraction
x-1
#Multiplication
x*2

#Division
x/2

#Int Division

(x*100)//3

#Mod
(((x*100)//3)%2)

#power

x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

Element wise Operations

In [66]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])
tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])


In [81]:
# tensor Addition
a+b

# tensor Sub

a-b

#Multiplication

a*b

# Division

a/b

# power

a **b

# Mod

(a*100)%(b*100)

# floor division

(a*100)//(b*100)

# absolute

c = torch.tensor([1,-2,3,-4]) 
torch.abs(c)


# Negative

torch.neg(c)

# Round
d = torch.tensor([1.3,2.5,3.7])
torch.round(d)

# ceil (round towards max (upper))

torch.ceil(d)

# floor (round towards minimum or lower )
torch.floor(d)


# clamp

torch.clamp(d,min=2,max=3)



tensor([2.0000, 2.5000, 3.0000])

Reduction Operation


In [89]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

f = torch.randint(size=(2,3),low=0, high=10,dtype=torch.float32)
e

tensor([[2., 6., 7.],
        [7., 8., 3.]])

In [ ]:
# Sum
torch.sum(e)

# sum along columns 
torch.sum(e,dim=0)

# sum along rows
torch.sum(e,dim=1)

# mean
torch.mean(e)

# mean along column
torch.mean(e,dim=0)

#mea along row
torch.mean(e,dim=1)

# Median 
torch.median(e)

#Max
torch.max(e)

# Min
torch.min(e)

#Product
torch.prod(e)

# Standard Deviation 
torch.std(e)


# Variance

torch.var(e)


# argmax

# (tells the position of the biggest item )

torch.argmax(e)

#argmin
# (tells the position of the smallest item )

torch.argmin(e)

tensor(0)

Matrix Operations


In [106]:
f = torch.randint(size=(2,3),low=0, high=10,dtype=torch.float32)

g = torch.randint(size=(3,4
),low=0, high=10,dtype=torch.float32)

In [107]:
# matrix multiplications

torch.matmul(f,g)

tensor([[60., 58., 46., 29.],
        [20., 24., 18.,  8.]])

In [113]:
vector_1 = torch.tensor([1,2])

vector_2 = torch.tensor([3,4])

# dot product

torch.dot(vector_1,vector_2)


# transpose 

torch.transpose(f,0,1)


# determinant - (square matrix only)

h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

torch.det(h)

# inverse (square matrix)

torch.inverse(h)

tensor([[-0.1154, -0.3846,  0.4615],
        [ 0.0513,  0.2821, -0.2051],
        [ 0.1731,  0.0769, -0.1923]])

Comparison Operations


In [116]:
i = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
j = torch.randint(size =(2,3), low=0, high =10, dtype=torch.float32)

print(i)
print(j)

tensor([[0., 2., 2.],
        [3., 7., 1.]])
tensor([[5., 0., 2.],
        [3., 7., 0.]])


In [122]:
# greater than
i>j
# less than 
i<j
#  equal to 
i==j

# not equal to
i!= j

# greater than or equal to
i>=j

# less than or equal to
i<=j

tensor([[ True, False,  True],
        [ True,  True, False]])

Special functions


In [124]:
k = torch.randint(size=(2,3),low=0, high = 10,dtype=torch.float32)
print(k)

tensor([[5., 3., 6.],
        [7., 8., 1.]])


In [130]:
# log
torch.log(k)

# exp
torch.exp(k)

# sqrt
torch.sqrt(k)

# sigmoid
torch.sigmoid(k)

# softmax
torch.softmax(k, dim=1)

#  relu 
torch.relu(k)

tensor([[5., 3., 6.],
        [7., 8., 1.]])

Inplace Operations

In [131]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3673, 0.1770, 0.2966],
        [0.9925, 0.2103, 0.1292]])
tensor([[0.1719, 0.9127, 0.6818],
        [0.1953, 0.9991, 0.1133]])


In [135]:
print(m.add_(n))
print(m)

tensor([[0.8830, 2.9151, 2.3419],
        [1.5785, 3.2076, 0.4692]])
tensor([[0.8830, 2.9151, 2.3419],
        [1.5785, 3.2076, 0.4692]])


In [137]:
torch.relu(m)
m.relu_()

tensor([[0.8830, 2.9151, 2.3419],
        [1.5785, 3.2076, 0.4692]])

Copying a tensor

In [138]:
a = torch.rand(2,3)
a

tensor([[0.0135, 0.1450, 0.7819],
        [0.3134, 0.2983, 0.3436]])

In [ ]:
b = a      #Not Good as its not copying the elements rather creating a reference named as b on a so if a changes b will also change and its not desirable
 

In [140]:
b

tensor([[0.0135, 0.1450, 0.7819],
        [0.3134, 0.2983, 0.3436]])

In [142]:
a[0][0] = 0
a

tensor([[0.0000, 0.1450, 0.7819],
        [0.3134, 0.2983, 0.3436]])

In [144]:
b

tensor([[0.0000, 0.1450, 0.7819],
        [0.3134, 0.2983, 0.3436]])

In [146]:
print(id(a))
print(id(b))

133325079715088
133325079715088


In [ ]:
b = a.clone()       # Cloning is a better way of copying


print(a)
print(b)
print(id(a))
print(id(b))

a[0][0] = 1

print(a)
print(b)

tensor([[0.0000, 0.1450, 0.7819],
        [0.3134, 0.2983, 0.3436]])
tensor([[0.0000, 0.1450, 0.7819],
        [0.3134, 0.2983, 0.3436]])
133325079715088
133325050671056
tensor([[1.0000, 0.1450, 0.7819],
        [0.3134, 0.2983, 0.3436]])
tensor([[0.0000, 0.1450, 0.7819],
        [0.3134, 0.2983, 0.3436]])


In [151]:
import time 


In [153]:
device_gpu = torch.device('cuda')
device_cpu = torch.device('cpu')
print(device_gpu)
print(device_cpu)

cuda
cpu


In [154]:
# creating a tensor on gpu 
torch.rand((2,3),device=device_gpu)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [157]:
# creating a tensor on cpu
a_cpu = torch.rand((2,3),device=device_cpu)

In [159]:
# moving existing tensor on gpu
a_cpu.to(device=device_gpu)
a_cpu + 5

tensor([[5.3041, 5.9867, 5.1290],
        [5.6887, 5.1637, 5.0899]])

In [162]:
#  Comparison of cpu and gpu 
size = 10000

# create random matrix on cpu
matrix_cpu_1 = torch.rand(size,size)
matrix_cpu_2 = torch.rand(size,size)


#  time measure on cpu
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu_1,matrix_cpu_2)

cpu_time = time.time() - start_time

print(f"Time on cpu : {cpu_time: .4f} seconds")

# Move Matrix on gpu 

matrix_gpu_1 = matrix_cpu_1.to('cuda')
matrix_gpu_2 = matrix_cpu_2.to('cuda')

#  time measure on gpu
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu_1,matrix_gpu_2)
torch.cuda.synchronize()  # Ensure all GPU operations are complete 

gpu_time = time.time() - start_time

print(f"Time on gpu : {gpu_time: .4f} seconds")


Time on cpu :  15.6132 seconds
Time on gpu :  0.6591 seconds


Reshaping Tensors

In [163]:
a = torch.ones(4,4)

In [166]:
#  reshape
a.reshape(4,2,2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [167]:
#  flatten

a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [173]:
# Permute

a = torch.rand(2,3,4)
print(a.shape)
print(a.permute(2,0,1))

a.permute(2,0,1).shape

torch.Size([2, 3, 4])
tensor([[[7.5480e-01, 6.0681e-01, 7.1649e-02],
         [5.6615e-01, 1.2770e-01, 9.7444e-01]],

        [[4.2627e-01, 8.9317e-01, 2.2347e-01],
         [2.6116e-01, 9.6507e-01, 7.5365e-01]],

        [[6.8710e-01, 5.4598e-04, 3.2925e-01],
         [4.4167e-01, 7.9697e-01, 7.5079e-01]],

        [[1.5191e-02, 9.9825e-01, 7.3508e-01],
         [9.1883e-01, 4.3148e-01, 3.9954e-01]]])


torch.Size([4, 2, 3])

In [ ]:
# Unsqueeze
# Image size  = 226, 226, 3
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [182]:
# Squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

Numpy and Pytorch

In [183]:
import numpy as np

In [185]:
a = torch.tensor([1,2,3])
b = a.numpy()
type(b)

numpy.ndarray

In [187]:
c = np.array([1,2,4])
c

array([1, 2, 4])

In [188]:
torch.from_numpy(c)

tensor([1, 2, 4])